### ISSUE TITLE
Standing Maintainathon Time

### ISSUE THREAD

**Issue by RichardLitt** [nock/welcome#4]
We've been having maintainathons for a few months now. Most of these have been ad hoc, set up at some point by me or @gr2m when we realize it might be a good time for another one. Yesterday, both of us wondered if perhaps we should have a set time each month for a recurring session, instead of ad hoc and prepared a couple of weeks before. This would help us figure out the best time to work on it. 

I'd like to suggest the second Friday of the month, at 12-4pm EST. 

@paulmelnikow What do you think?

**Comment by paulmelnikow** [comment]
Sounds good to me!

**Comment by RichardLitt** [comment]
Alright, I've set it up. I've updated [nock/nock#1268](https://github.com/nock/nock/issues/1268) with the details. :)

**Comment by paulmelnikow** [comment]
Hey @RichardLitt, just a heads-up that the GCal link isn't working for me:

<img width="333" alt="Screen Shot 2019-03-26 at 9 56 41 AM" src="https://user-images.githubusercontent.com/1487036/55002808-9b99df80-4fad-11e9-910e-3b69d95d86fe.png">

**Comment by RichardLitt** [comment]
Perhaps this? <a target="_blank" href="https://calendar.google.com/event?action=TEMPLATE&amp;tmeid=NWduZ2ZyZzZqZnRzbG1sNDA3bmNvaTRsMWlfMjAxOTA0MTJUMTYwMDAwWiByaWNoYXJkQGJ1cm50ZmVuLmNvbQ&amp;tmsrc=richard%40burntfen.com&amp;scp=ALL"><img border="0" src="https://www.google.com/calendar/images/ext/gc_button1_en.gif"></a>

**Comment by RichardLitt** [comment]
This should work: https://calendar.google.com/event?action=TEMPLATE&tmeid=NWduZ2ZyZzZqZnRzbG1sNDA3bmNvaTRsMWlfMjAxOTA0MTJUMTYwMDAwWiBidXJudGZlbi5jb21fbjZqMWsycWlhN2NiOW8zdTdoNGo4YjNmOThAZw&tmsrc=burntfen.com_n6j1k2qia7cb9o3u7h4j8b3f98%40group.calendar.google.com&scp=ALL

**Comment by gr2m** [comment]
Thanks Richard, that works for me!
