### ISSUE TITLE
Close down the Calendar invite

### ISSUE THREAD

**Issue by RichardLitt** [nock/welcome#7]
At the moment, we have a standing invite for a Nock maintainathon on the calendar. I haven't made it in a long time. Should I remove the event and references to it, as we're not actively doing this at the moment?

**Comment by gr2m** [comment]
I'd say yes, I do not have the invite in my own calendar

**Comment by RichardLitt** [comment]
OK. I've deleted it, closed https://github.com/nock/welcome/issues/4, and also closed the old Updates thread as it hasn't been updated in over a year. 

This doesn't mean I wouldn't be opposed to hanging out and hacking again sometime. :) We just don't need the standing invite.
